### ISSUE TITLE
The connection string is missing the property: HostName

### ISSUE THREAD

**Issue by LastTribunal** [formulahendry/vscode-azure-iot-toolkit#19]
I didnt configure it, just installed it
this thing should be disabled by default, so it doesn't try to connect

**Comment by formulahendry** [comment]
Hi @LastTribunal , could you please go to `File`->`Preference`->`Settings` to see whether there is a config of `"azure-iot-toolkit.iotHubConnectionString"`?

**Comment by LastTribunal** [comment]
I uninstalled it, but I think there was this setting, and it had and empty string for a value.  I never configured it

**Comment by formulahendry** [comment]
If you just set an empty string or a valid IoT Hub connection string, this error will not occur. This error message will only show when you set an invalid IoT Hub connection string.

**Comment by LastTribunal** [comment]
There was an empty string originally, i did not make any changes, all I did is install the product and it caused the error.  this should not be,.  But it makes zero diff to me, I uninstalled it and it is gone.  I wasn't using it and probably not many are,.. good luck
