### ISSUE TITLE
"The connection string is missing the property: SharedAccessKeyName"

### ISSUE THREAD

**Issue by ziziz** [formulahendry/vscode-azure-iot-toolkit#20]
Getting this message when trying to initiate. trying the following format directly copied from the azure portal: `HostName=my-azure-hostname.azure-devices.net;ShareAccessKeyName=iothubowner;SharedAccessKey=XXXXXXXXX...=`
In settings for     `"azure-iot-toolkit.iotHubConnectionString" `the same string in dubble quotes.

What am I missing here?

**Comment by formulahendry** [comment]
Yes, this is correct. Something like below:
![image](https://user-images.githubusercontent.com/1050213/29398365-de49e016-8356-11e7-9776-79c2cca58c64.png)

Could you share your screenshot?

**Comment by formulahendry** [comment]
Oh! I just find that your iotHubConnectionString is using **ShareAccessKeyName** not **SharedAccessKeyName**.
You just missed **d** in **Shared**.

**Comment by ziziz** [comment]
Here you go!  https://l.comturial.com/2v4biXn

**Comment by formulahendry** [comment]
Could you try using **SharedAccessKeyName** instead of **ShareAccessKeyName**?

**Comment by ziziz** [comment]
Ah! Got it! Thanks :)

**Comment by formulahendry** [comment]
Closing then. 😄

**Comment by zaphodtx** [comment]
I had to remove the brackets to that were in the example to get this working.
